### ISSUE TITLE
(WEB)cam use

### ISSUE THREAD

**Issue by Hugodriverless** [fediazgon/cone-detector-tf#1]
I'm not able to get the code working with my webcam or external cam, is it possible to do it?
I tried the following without any results : 

def main():
    # Read TensorFlow graph
    detection_graph = tf_utils.load_model(FROZEN_GRAPH_PATH)

    # Read video from disk and count frames
    cap = cv2.VideoCapture(0)

    while(True):
    # Capture frame-by-frame
    ret, frame = cap.read()
    fps = cap.get(cv2.CAP_PROP_FPS)

King in regards,

**Comment by fediazgon** [comment]
Thanks for your interest in the project. I think this is solved by https://github.com/fdiazgon/cone-detector-tf/commit/076510ac603e4092902ac4cef14e9f484ae043a3. Please, pull from master and try again.

Also, remember to change `CROP_WIDTH` and `CROP_HEIGHT` according to the resolution of your camera. Otherwise, it will use 600 or the whole image (whichever dimension is lower).

**Comment by Hugodriverless** [comment]
I'm really thankful for your reply, the code is working for me know.

kind regards,
